### ISSUE TITLE
TypeError: object is not a function

### ISSUE THREAD

**Issue by awinogradov** [dfilatov/vow-fs#18]
Вызов:
``` js
app.use(require('enb/lib/server/server-middleware').createMiddleware({
    cdir : process.cwd(),
    noLog : false
}));
```

``` bash
TypeError: object is not a function
    at Object.<anonymous> (/Users/verybigman/Sources/test/node_modules/borschik/node_modules/vow-fs/lib/fs.js:13:22)
    at Module._compile (module.js:444:26)
    at Object.Module._extensions..js (module.js:462:10)
    at Module.load (module.js:339:32)
    at Function.Module._load (module.js:294:12)
    at Module.require (module.js:349:17)
    at require (module.js:368:17)
    at Object.<anonymous> (/Users/verybigman/Sources/test/node_modules/borschik/lib/util.js:3:13)
    at Module._compile (module.js:444:26)
    at Object.Module._extensions..js (module.js:462:10)
```

__UPD__: vow-fs 0.3.2 borschik 1.3.2

**Comment by dfilatov** [comment]
Очень сложно по такому логу сказать тебе что-то внятное.

**Comment by verybigman** [comment]
@dfilatov скажи чего дать тебе?:)

**Comment by dfilatov** [comment]
Я вообще сомневаюсь, что это проблема в vow-fs. Ты мог чуть больше подебажить свой проект и сказать, например, что именно там за `object is not a function`?

**Comment by verybigman** [comment]
Ок! Завтра займусь
